HomeWorkWeekOne/Controllers/BankController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HomeWorkWeekOne.Models;

namespace HomeWorkWeekOne.Controllers
{
    public class BankController : Controller
    {
        private 客戶資料Entities db = new 客戶資料Entities();

        // GET: /Bank/
        public ActionResult Index(int? id)
        {
            var 客戶銀行資訊 = db.客戶銀行資訊.Include(客 => 客.客戶資料);
            if (id != null)
            {
                Session["CustomerId"] = id;
                return View(客戶銀行資訊.Where(x => x.客戶Id == id).ToList());
            }
            else
            {
                return View(客戶銀行資訊.ToList());
            }

        }

        // GET: /Bank/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶銀行資訊 客戶銀行資訊 = db.客戶銀行資訊.Find(id);
            if (客戶銀行資訊 == null)
            {
                return HttpNotFound();
            }
            return View(客戶銀行資訊);
        }

        // GET: /Bank/Create
        public ActionResult Create(int? id)
        {
            ViewBag.客戶Id = new SelectList(db.客戶資料, "Id", "客戶名稱");
            return View();
        }

        // POST: /Bank/Create
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Id,客戶Id,銀行名稱,銀行代碼,分行代碼,帳戶名稱,帳戶號碼,停用")] 客戶銀行資訊 客戶銀行資訊)
        {
            if (ModelState.IsValid)
            {
                db.客戶銀行資訊.Add(客戶銀行資訊);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.客戶Id = new SelectList(db.客戶資料, "Id", "客戶名稱", 客戶銀行資訊.客戶Id);
            return View(客戶銀行資訊);
        }

        // GET: /Bank/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶銀行資訊 客戶銀行資訊 = db.客戶銀行資訊.Find(id);
            if (客戶銀行資訊 == null)
            {
                return HttpNotFound();
            }
            ViewBag.客戶Id = new SelectList(db.客戶資料, "Id", "客戶名稱", 客戶銀行資訊.客戶Id);
            return View(客戶銀行資訊);
        }

        // POST: /Bank/Edit/5
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,客戶Id,銀行名稱,銀行代碼,分行代碼,帳戶名稱,帳戶號碼,停用")] 客戶銀行資訊 客戶銀行資訊)
        {
            if (ModelState.IsValid)
            {
                db.Entry(客戶銀行資訊).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.客戶Id = new SelectList(db.客戶資料, "Id", "客戶名稱", 客戶銀行資訊.客戶Id);
            return View(客戶銀行資訊);
        }

        // GET: /Bank/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶銀行資訊 客戶銀行資訊 = db.客戶銀行資訊.Find(id);
            if (客戶銀行資訊 == null)
            {
                return HttpNotFound();
            }
            return View(客戶銀行資訊);
        }

        // POST: /Bank/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            客戶銀行資訊 客戶銀行資訊 = db.客戶銀行資訊.Find(id);
            客戶銀行資訊.停用 = true;
            //db.客戶銀行資訊.Remove(客戶銀行資訊);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HomeWorkWeekOne/Views/Bank/Create.cshtml
@model HomeWorkWeekOne.Models.客戶銀行資訊

@{
    ViewBag.Title = "客戶銀行資訊新增";
}

<h2>客戶銀行資訊新增</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>客戶銀行資訊</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.客戶Id, "客戶Id", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("客戶Id", String.Empty)
                @Html.ValidationMessageFor(model => model.客戶Id)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.銀行名稱, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.銀行名稱)
                @Html.ValidationMessageFor(model => model.銀行名稱)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.銀行代碼, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.銀行代碼)
                @Html.ValidationMessageFor(model => model.銀行代碼)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.分行代碼, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.分行代碼)
                @Html.ValidationMessageFor(model => model.分行代碼)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.帳戶名稱, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.帳戶名稱)
                @Html.ValidationMessageFor(model => model.帳戶名稱)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.帳戶號碼, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.帳戶號碼)
                @Html.ValidationMessageFor(model => model.帳戶號碼)
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.停用, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.停用)
                @Html.ValidationMessageFor(model => model.停用)
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="儲存" class="button-warning pure-button" />
                <input type="button" value="返回客戶銀行資訊管理" class="pure-button" onclick="location.href='@Url.Action("Index", "Bank", new { id = Session["CustomerId"] })'" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HomeWorkWeekOne/Views/Bank/Delete.cshtml
@model HomeWorkWeekOne.Models.客戶銀行資訊

@{
    ViewBag.Title = "客戶銀行資訊刪除";
}

<h2>客戶銀行資訊刪除</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>客戶銀行資訊</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.銀行名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.銀行名稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.銀行代碼)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.銀行代碼)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.分行代碼)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.分行代碼)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.帳戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.帳戶名稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.帳戶號碼)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.帳戶號碼)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.停用)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.停用)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.客戶資料.客戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.客戶資料.客戶名稱)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="刪除" class="button-error pure-button" />
            <input type="button" value="返回客戶銀行資訊管理" class="pure-button" onclick="location.href='@Url.Action("Index", "Bank")'" />
        @*<input type="submit" value="Delete" class="btn btn-default" /> |
        @Html.ActionLink("Back to List", "Index")*@
        </div>
    }
</div>

HomeWorkWeekOne/Views/Bank/Details.cshtml
@model HomeWorkWeekOne.Models.客戶銀行資訊

@{
    ViewBag.Title = "客戶銀行資訊";
}

<h2>客戶銀行資訊</h2>

<div>
    <h4>客戶銀行資訊</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.銀行名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.銀行名稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.銀行代碼)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.銀行代碼)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.分行代碼)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.分行代碼)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.帳戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.帳戶名稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.帳戶號碼)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.帳戶號碼)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.停用)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.停用)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.客戶資料.客戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.客戶資料.客戶名稱)
        </dd>

    </dl>
</div>
<p>
    <input type="button" value="編輯" class="button-success pure-button" onclick="location.href='@Url.Action("Edit", "Bank", new { id = Model.Id })'" />
    <input type="button" value="返回客戶銀行資訊管理" class="pure-button" onclick="location.href='@Url.Action("Index", "Bank")'" />
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")*@
</p>

HomeWorkWeekOne/Views/Bank/Edit.cshtml
@model HomeWorkWeekOne.Models.客戶銀行資訊

@{
    ViewBag.Title = "客戶銀行資訊編輯";
}

<h2>客戶銀行資訊編輯</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>客戶銀行資訊</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.客戶Id, "客戶Id", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("客戶Id", String.Empty)
                @Html.ValidationMessageFor(model => model.客戶Id)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.銀行名稱, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.銀行名稱)
                @Html.ValidationMessageFor(model => model.銀行名稱)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.銀行代碼, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.銀行代碼)
                @Html.ValidationMessageFor(model => model.銀行代碼)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.分行代碼, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.分行代碼)
                @Html.ValidationMessageFor(model => model.分行代碼)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.帳戶名稱, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.帳戶名稱)
                @Html.ValidationMessageFor(model => model.帳戶名稱)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.帳戶號碼, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.帳戶號碼)
                @Html.ValidationMessageFor(model => model.帳戶號碼)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.停用, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.停用)
                @Html.ValidationMessageFor(model => model.停用)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="儲存" class="button-warning pure-button" />
                <input type="button" value="返回客戶銀行資訊管理" class="pure-button" onclick="location.href='@Url.Action("Index", "Bank")'" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HomeWorkWeekOne/Views/Bank/Index.cshtml
@model IEnumerable<HomeWorkWeekOne.Models.客戶銀行資訊>

@{
    ViewBag.Title = "客戶銀行資料管理";
}

<h2>客戶銀行資料管理</h2>

<p>
    <input type="button" value="新增" class="pure-button" onclick="location.href='@Url.Action("Create", "Bank", new { id = Session["CustomerId"] })'" />
    <input type="button" value="返回客戶管理" class="pure-button" onclick="location.href='@Url.Action("Index", "Customer")'" />
    @*@Html.ActionLink("Create New", "Create")*@
</p>
<table class="pure-table pure-table-horizontal">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.銀行名稱)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.銀行代碼)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.分行代碼)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.帳戶名稱)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.帳戶號碼)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.停用)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.客戶資料.客戶名稱)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.銀行名稱)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.銀行代碼)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.分行代碼)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.帳戶名稱)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.帳戶號碼)
                </td>
                <td style="text-align:center;">
                    @Html.DisplayFor(modelItem => item.停用)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.客戶資料.客戶名稱)
                </td>
                <td>
                    <input type="button" value="編輯" class="button-success pure-button" onclick="location.href='@Url.Action("Edit", "Bank", new { id = item.Id })'" />
                    <input type="button" value="明細" class="button-secondary pure-button" onclick="location.href='@Url.Action("Details", "Bank", new { id = item.Id })'" />
                    <input type="button" value="刪除" class="button-error pure-button" onclick="location.href='@Url.Action("Delete", "Bank", new { id = item.Id })'" />
                </td>
            </tr>
        }
    </tbody>



</table>