HomeWorkWeekOne/Controllers/ContactPersonController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HomeWorkWeekOne.Models;

namespace HomeWorkWeekOne.Controllers
{
    public class ContactPersonController : Controller
    {
        private 客戶資料Entities db = new 客戶資料Entities();

        // GET: /ContactPerson/
        public ActionResult Index(int? id)
        {
            var 客戶聯絡人 = db.客戶聯絡人.Include(客 => 客.客戶資料);
            if (id != null)
            {
                Session["CustomerId"] = id;
                return View(客戶聯絡人.Where(x => x.客戶Id == id).ToList());
            }
            else
            {
                return View(客戶聯絡人.ToList());
            }
        }

        // GET: /ContactPerson/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶聯絡人 客戶聯絡人 = db.客戶聯絡人.Find(id);
            if (客戶聯絡人 == null)
            {
                return HttpNotFound();
            }
            return View(客戶聯絡人);
        }

        // GET: /ContactPerson/Create
        public ActionResult Create(int? id)
        {
            ViewBag.客戶Id = new SelectList(db.客戶資料, "Id", "客戶名稱");
            return View();
        }

        // POST: /ContactPerson/Create
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Id,客戶Id,職稱,姓名,Email,手機,電話,停用")] 客戶聯絡人 客戶聯絡人)
        {
            if (ModelState.IsValid)
            {
                var people = db.客戶聯絡人.Where(x => x.Email == 客戶聯絡人.Email).FirstOrDefault();
                if (people != null)
                {
                    TempData["msg"] = "<script>alert('Email不可以重複');</script>";
                    //throw new Exception("Email不可以重複");
                }
                else
                {
                    
                    db.客戶聯絡人.Add(客戶聯絡人);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

            }

            ViewBag.客戶Id = new SelectList(db.客戶資料, "Id", "客戶名稱", 客戶聯絡人.客戶Id);
            return View(客戶聯絡人);
        }

        // GET: /ContactPerson/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶聯絡人 客戶聯絡人 = db.客戶聯絡人.Find(id);
            if (客戶聯絡人 == null)
            {
                return HttpNotFound();
            }
            ViewBag.客戶Id = new SelectList(db.客戶資料, "Id", "客戶名稱", 客戶聯絡人.客戶Id);
            return View(客戶聯絡人);
        }

        // POST: /ContactPerson/Edit/5
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,客戶Id,職稱,姓名,Email,手機,電話,停用")] 客戶聯絡人 客戶聯絡人)
        {
            if (ModelState.IsValid)
            {
                var people = db.客戶聯絡人.Where(x => x.Email == 客戶聯絡人.Email).FirstOrDefault();
                if (people != null)
                {
                    TempData["msg"] = "<script>alert('Email不可以重複');</script>";
                    //throw new Exception("Email不可以重複");
                }
                else
                {
                    db.Entry(客戶聯絡人).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            ViewBag.客戶Id = new SelectList(db.客戶資料, "Id", "客戶名稱", 客戶聯絡人.客戶Id);
            return View(客戶聯絡人);
        }

        // GET: /ContactPerson/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶聯絡人 客戶聯絡人 = db.客戶聯絡人.Find(id);
            if (客戶聯絡人 == null)
            {
                return HttpNotFound();
            }
            return View(客戶聯絡人);
        }

        // POST: /ContactPerson/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            客戶聯絡人 客戶聯絡人 = db.客戶聯絡人.Find(id);
            客戶聯絡人.停用 = true;
            //db.客戶聯絡人.Remove(客戶聯絡人);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


    }
}

HomeWorkWeekOne/Views/ContactPerson/Create.cshtml
@model HomeWorkWeekOne.Models.客戶聯絡人

@{
    ViewBag.Title = "客戶聯絡人新增";
}

<h2>客戶聯絡人新增</h2>
@Html.Raw(TempData["msg"])

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>客戶聯絡人</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.客戶Id, "客戶Id", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("客戶Id", String.Empty)
                @Html.ValidationMessageFor(model => model.客戶Id)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.職稱, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.職稱)
                @Html.ValidationMessageFor(model => model.職稱)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.姓名, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.姓名)
                @Html.ValidationMessageFor(model => model.姓名)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.手機, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.手機)
                @Html.ValidationMessageFor(model => model.手機)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.電話, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.電話)
                @Html.ValidationMessageFor(model => model.電話)
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.停用, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.停用)
                @Html.ValidationMessageFor(model => model.停用)
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="儲存" class="button-warning pure-button" />
                <input type="button" value="返回客戶聯絡人管理" class="pure-button" onclick="location.href='@Url.Action("Index", "ContactPerson", new { id = Session["CustomerId"] })'" />
                @*<input type="submit" value="Create" class="btn btn-default" />*@
            </div>
        </div>
    </div>
}

@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HomeWorkWeekOne/Views/ContactPerson/Delete.cshtml
@model HomeWorkWeekOne.Models.客戶聯絡人

@{
    ViewBag.Title = "客戶聯絡人刪除";
}

<h2>客戶聯絡人刪除</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>客戶聯絡人</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.職稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.職稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.姓名)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.姓名)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.手機)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.手機)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.電話)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.電話)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.停用)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.停用)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.客戶資料.客戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.客戶資料.客戶名稱)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="刪除" class="button-error pure-button" />
            <input type="button" value="返回客戶聯絡人管理" class="pure-button" onclick="location.href='@Url.Action("Index", "ContactPerson")'" />
        </div>
    }
</div>

HomeWorkWeekOne/Views/ContactPerson/Details.cshtml
@model HomeWorkWeekOne.Models.客戶聯絡人

@{
    ViewBag.Title = "客戶聯絡人";
}

<h2>客戶聯絡人</h2>

<div>
    <h4>客戶聯絡人</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.職稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.職稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.姓名)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.姓名)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.手機)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.手機)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.電話)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.電話)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.停用)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.停用)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.客戶資料.客戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.客戶資料.客戶名稱)
        </dd>

    </dl>
</div>
<p>
    <input type="button" value="編輯" class="button-success pure-button" onclick="location.href='@Url.Action("Edit", "ContactPerson", new { id = Model.Id })'" />
    <input type="button" value="返回客戶聯絡人管理" class="pure-button" onclick="location.href='@Url.Action("Index", "ContactPerson")'" />
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")*@
</p>

HomeWorkWeekOne/Views/ContactPerson/Edit.cshtml
@model HomeWorkWeekOne.Models.客戶聯絡人

@{
    ViewBag.Title = "客戶聯絡人編輯";
}
@Html.Raw(TempData["msg"])
<h2>客戶聯絡人編輯</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>客戶聯絡人</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.客戶Id, "客戶Id", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("客戶Id", String.Empty)
                @Html.ValidationMessageFor(model => model.客戶Id)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.職稱, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.職稱)
                @Html.ValidationMessageFor(model => model.職稱)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.姓名, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.姓名)
                @Html.ValidationMessageFor(model => model.姓名)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.手機, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.手機)
                @Html.ValidationMessageFor(model => model.手機)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.電話, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.電話)
                @Html.ValidationMessageFor(model => model.電話)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.停用, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.停用)
                @Html.ValidationMessageFor(model => model.停用)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="儲存" class="button-warning pure-button" />
                <input type="button" value="返回客戶聯絡人管理" class="pure-button" onclick="location.href='@Url.Action("Index", "ContactPerson")'" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HomeWorkWeekOne/Views/ContactPerson/Index.cshtml
@model IEnumerable<HomeWorkWeekOne.Models.客戶聯絡人>

@{
    ViewBag.Title = "客戶聯絡人管理";
}

<h2>客戶聯絡人管理</h2>

<p>
    <input type="button" value="新增" class="pure-button" onclick="location.href='@Url.Action("Create", "ContactPerson", new { id = Session["CustomerId"] })'" />
    <input type="button" value="返回客戶管理" class="pure-button" onclick="location.href='@Url.Action("Index", "Customer")'" />
    @*@Html.ActionLink("Create New", "Create")*@
</p>
<table class="pure-table pure-table-horizontal">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.職稱)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.姓名)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.手機)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.電話)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.停用)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.客戶資料.客戶名稱)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.職稱)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.姓名)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.手機)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.電話)
                </td>
                <td style="text-align:center;">
                    @Html.DisplayFor(modelItem => item.停用)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.客戶資料.客戶名稱)
                </td>
                <td>
                    <input type="button" value="編輯" class="button-success pure-button" onclick="location.href='@Url.Action("Edit", "ContactPerson", new { id = item.Id })'" />
                    <input type="button" value="明細" class="button-secondary pure-button" onclick="location.href='@Url.Action("Details", "ContactPerson", new { id = item.Id })'" />
                    <input type="button" value="刪除" class="button-error pure-button" onclick="location.href='@Url.Action("Delete", "ContactPerson", new { id = item.Id })'" />
                </td>
            </tr>
        }
    </tbody>



</table>